blog/urls.py
from django.conf.urls import url


urlpatterns = [
]

catalog/urls.py
from django.conf.urls import url
from catalog import views

urlpatterns = [
    url(r'^search/$', views.search, name='search'),
    url(r'^product/(?P<product_id>[0-9]+)/$', views.list_substitute, name='list_substitute'),
    url(r'^substitute/(?P<substitute_id>[0-9]+)/$', views.detail_substitute, name='detail_substitute'),
    url(r'^legal/$', views.legal, name='legal'),
    url(r'^categories/$', views.list_categories, name='list_categories'),
    url(r'^products/$', views.list_products, name='list_products'),
]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import path
from catalog import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url


urlpatterns = [
    # For security reasons, it is essential to change the admin URL because hackers know it
    path('admin', admin.site.urls),
    url(r'^$', views.index, name="index"),
    url(r'^catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^blog/', include(('blog.urls', 'blog'), namespace='blog')),
]

"""if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns"""

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from users import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^log_in/$', views.log_in, name='log_in'),
    url(r'^log_out/$', views.log_out, name="log_out"),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^save_product/(?P<sub_id>[0-9]+)/$', views.save_product, name='save_product'),
    url(r'^list_saved_products/$', views.list_saved_products, name='list_saved_products'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html', email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt', success_url='/users/password_reset/done/'),
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html', success_url='/users/reset/done/'),
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class EditProfile(models.Model):
    about_me = models.TextField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.about_me

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):

    # I added this function so that the email is unique
    def clean_email(self):
        """This function return an error message if the email has already been taken"""

        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Cet Email à déjà été pris.')
        return email

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ConnexionForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur")
    password = forms.CharField(label='Mot de passe', widget=forms.PasswordInput)


class EditProfileForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur")
    about_me = forms.CharField(widget=forms.Textarea(attrs={'style':'width: 100%;'}), label='A propos de moi')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username


    # This function ensures that when the user changes his username, he does not take the one of another
    def clean_username(self):
        """This function return an error message if the username has already been taken"""

        username = self.cleaned_data['username']
        if username != self.original_username:
            # The user can not take a username if it is already in the database
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError('Ce nom d\'utilisateur est déjà pris.')
        return username

users/views.py
from django.contrib.auth import login, authenticate, logout
from users.forms import SignUpForm, ConnexionForm, EditProfileForm
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from catalog.models import Substitute
from users.models import EditProfile
from blog.models import Comment
from django.db import transaction



def signup(request):
    title = 'Inscription'

    if request.user.is_authenticated:
        return redirect('index')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Félicitations, vous étes maintenant un utilisateur enregistré!')
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form ,'title': title})


def log_in(request):
    title = 'Connexion'
    error = False
    next = request.GET.get('next')
    if request.user.is_authenticated:
        return redirect('index')
    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)  # We check if the data is correct
            if user and next is None:  # If the returned object is not None
                login(request, user)  # we connect the user
                messages.add_message(request, messages.SUCCESS,
                                     f'Vous êtes connecté {username}')
                return redirect('index')
            elif user and next is not None:
                login(request, user)
                return redirect(next)
            else: # otherwise an error will be displayed
                error = True
    else:
        form = ConnexionForm()

    return render(request, 'users/login.html', locals())


def log_out(request):
    logout(request)
    return redirect(reverse('users:log_in'))


@login_required
def profile(request):
    title = 'Profile'

    current_user = get_object_or_404(User, id=request.user.id)
    if 'comment_author_id' in request.GET:
        comment_author_id = request.GET['comment_author_id'] 
        comment_author = get_object_or_404(User, id=comment_author_id)
        comments = Comment.objects.filter(author=comment_author).order_by('-date_added')
        edits = EditProfile.objects.filter(user=comment_author)
    else:
        comments = Comment.objects.filter(author=current_user).order_by('-date_added')
        edits = EditProfile.objects.filter(user=current_user)
  
    return render(request, 'users/profile.html', locals())


@login_required
def save_product(request, sub_id):
    user_id = request.user.id
    sub_id = int(sub_id)
    user = User.objects.filter(id=user_id)
    substitute = get_object_or_404(Substitute, id=sub_id)
    substitute.user_sub.add(user[0])

    return redirect('users:list_saved_products')


@login_required
def list_saved_products(request):
    title = 'Liste des produits sauvegarder'
    user_id = request.user.id
    user = User.objects.filter(id=user_id)
    # We select, since the relationship manytomany, all the substitutes that the user has saved
    substitutes = user[0].user_substitute.all()
    return render(request, 'users/list_saved_products.html', {'substitutes': substitutes, 'title': title})


@login_required
@transaction.atomic
def edit_profile(request):
    title = 'Editer le profile'

    if request.method == "POST":
        # request.user.username is the original username
        form = EditProfileForm(request.user.username, request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            about_me = form.cleaned_data["about_me"]
            user = get_object_or_404(User, id=request.user.id)

            # We use a transaction so that if one of the requests below fails all previous ones are canceled
            with transaction.atomic():
                edit = EditProfile.objects.filter(user=user)
                if edit.exists():
                    edit.update(about_me=about_me, user=user)
                    user.username = username
                    user.save()
                else:
                    edit = EditProfile(about_me=about_me, user=user)
                    user.username = username
                    edit.save()
                    user.save()
                messages.add_message(request, messages.SUCCESS,
                                        'Vos changements ont été enregistrés.')
                return redirect(reverse('users:profile'))
    else:
        edit = EditProfile.objects.filter(user=request.user)
        about_me = edit[0].about_me if edit.exists() else 'Décrivez vous en quelques mots'

        form = EditProfileForm(request.user.username,
                               {'username': request.user.username,
                                'about_me': about_me})
    return render(request, 'users/edit_profile.html', {'form': form ,'title': title})

users/templates/users/edit_profile.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
  <h1>Utilisateur : {{ user.username }}</h1>
  </div> 
{% endblock %}

{% block section_content %}
  <div class="row">
    <h2 class="col-xs-12">Editer le profile</h2>
  </div>
  <div class="row">
    <hr class="col-lg-offset-55 col-xs-1 line">
  </div>

  <div class="row">
    <form class="col-sm-offset-4 col-sm-6 col-xs-12" method="post">
      {% csrf_token %}
      {% for field in form %}
        <p class="field-form paragraph">
          {{ field.label_tag }}<br>
          {{ field }}<br>

          {% for error in field.errors %}
            <p class="error paragraph">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
      <button class="btn btn-primary btn-lg submit" type="submit">Soumettre</button>
    </form>
  </div>
{% endblock %}

users/templates/users/list_saved_products.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Utilisateur : {{ user.username }}</h1>
  </div> 
{% endblock %}

{% block section_content %}
  <div class="row">
      <h2 class="col-xs-12">Liste des produits sauvegarder</h2>
  </div>
  <div class="row">
    <hr class="col-lg-offset-55 col-xs-1 line">
  </div>

  {% if substitutes|length_is:"0" %}
    <div class="row">
      <h3>Vous n'avez aucun produit dans vos favoris</h3>
    </div>
  {% else %}
    <div class="row div-products">
      {% for substitute in substitutes %}
        <div class="col-sm-4">
          <div class="row div-product">
            <div class="col-sm-12 coloffset2 col-xs-8">
              <a class="link-product" href="{% url 'catalog:detail_substitute' substitute.id %}" title="{{ substitute1.name }}">
                <div class="div-img">
                  <img class="img-product" src="{{ substitute.picture.url }}" alt="{{ substitute.picture.name }}" />
                </div>
                <span class="nutriscore">
                  {% if 'nutriscore-a.svg' in substitute.nutri_score.url %}A
                  {% elif 'nutriscore-b.svg' in substitute.nutri_score.url %}B
                  {% elif 'nutriscore-c.svg' in substitute.nutri_score.url %}C
                  {% elif 'nutriscore-d.svg' in substitute.nutri_score.url %}D
                  {% elif 'nutriscore-e.svg' in substitute.nutri_score.url %}E
                  {% endif %}
                </span>
                <div class="product-name">{{ substitute.name|truncatewords:10 }}</div>
              </a>  
            </div> 
          </div> 
        </div>
        {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Connexion</h1>
  </div> 
{% endblock %}

{% block section_content %}
  <div class="row">
    <h2 class="col-xs-12">Se connecter</h2>
  </div>
  <div class="row">
    <hr class="col-lg-offset-55 col-xs-1 line">
  </div>

  {% if error %}
    <p class="paragraph"><strong>Utilisateur inconnu ou mauvais de mot de passe.</strong></p>
  {% endif %}
  <div class="row">
    <form class="col-sm-offset-4 col-sm-6 col-xs-12" method="post">
      {% csrf_token %}
      {% for field in form %}
      <p class="field-form paragraph">
        {{ field.label_tag }}<br>
        {{ field }}
      </p>
      {% endfor %}
      <input class="btn btn-primary btn-lg submit" type="submit" value="Se connecter" />
    </form>
  </div>
  
  <div class="row">
    <p class="col-sm-offset-2 col-sm-8 col-xs-12 redirect paragraph">Nouveau utilisateur? 
      <a href="{% url 'users:signup' %}">Cliquez ici pour vous enregistrer!</a>
    </p>
    <p class="col-sm-offset-2 col-sm-8 col-xs-12 redirect paragraph">Mot de passe oublier?
      <a href="{% url 'users:password_reset' %}">Cliquez ici pour le réinitialiser</a>
    </p>
  </div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Réinitialisation du mot de passe</h1>
  </div>
{% endblock %}

{% block section_content %}
  <div class="row">
    <p class="reset paragraph">
      Votre mot de passe a été défini. Vous pouvez y aller et vous <a href="{% url 'users:log_in' %}">connecter</a>
      maintenant.
    </p>
  </div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Nouveau mot de passe</h1>
  </div>
{% endblock %}

{% block section_content %}
  {% if validlink %}
    <div class="row">
      <h2 class="col-xs-12">Changer le mot de passe</h2>
    </div>
    <div class="row">
      <hr class="col-lg-offset-55 col-xs-1 line">
    </div>
    
    <div class="row">
      <form class="col-sm-offset-4 col-sm-6 col-xs-12" method="post">
        {% csrf_token %}
        {% for field in form %}
        <p class="field-form paragraph">
          {{ field.label_tag }}<br>
          {{ field }}
        </p>
        {% endfor %}
        <input class="btn btn-primary btn-lg submit" type="submit" value="Changer le mot de passe" />
      </form>
    </div>
    
  {% else %}
  <div class="row">
    <p class="reset paragraph">
      Le lien de réinitialisation du mot de passe n'était pas valide, probablement parce qu'il a déjà été utilisé.
      Veuillez demander une nouvelle réinitialisation du mot de passe.
    </p>
  </div>
    
  {% endif %}
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Message de réinitialisation</h1>
  </div>
{% endblock %}

{% block section_content %}
  <div class="row">
    <p class="reset paragraph">
      Nous vous avons envoyé des instructions pour définir votre mot de passe, si un compte existe avec le courrier que vous
      avez entré.
      Vous devriez les recevoir sous peu.
    </p>
  </div>
  <div class="row">
    <p class="reset paragraph">
      Si vous ne recevez pas d'e-mail, assurez-vous d'avoir entré l'adresse avec laquelle vous vous êtes inscrit.
      et vérifiez votre dossier de spam.
    </p>
  </div>
  
{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}

Pour lancer le processus de réinitialisation du mot de passe de votre compte Pur Beurre {{ user.username }}, 
cliquez sur le lien ci-dessous:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}


Si le lien ci-dessus ne fonctionne pas, veuillez copier et coller l'URL dans une nouvelle fenêtre.

Cordialement,
L'équipe Pur Beurre
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Réinitialisation du mot de passe</h1>
  </div>
{% endblock %}

{% block section_content %}
  <div class="row">
    <h2 class="col-xs-12">Mot de passe oublier</h2>
  </div>
  <div class="row">
    <hr class="col-lg-offset-55 col-xs-1 line">
  </div>

  <div class="row">
    <form class="col-sm-offset-4 col-sm-6 col-xs-12" method="post">
      {% csrf_token %}
      {% for field in form %}
      <p class="field-form paragraph">
        {{ field.label_tag }}
        {{ field }}
      </p>
      {% endfor %}
      <input class="btn btn-primary btn-lg submit" type="submit" value="Envoyer" />
    </form>
  </div>
  
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Utilisateur : {{ user.username }}</h1>
  </div> 
{% endblock %}

{% block section_content %}
  <div class="row">
    <h2 class="col-xs-12">Profile de l'utilisateur : {% if comment_author %}{{ comment_author.username }}{% else %}{{ user.username }}{% endif %}</h2>
  </div>
  <div class="row">
    <hr class="col-lg-offset-55 col-xs-1 line">
  </div>

  <div class='row'>
    <p class="col-sm-offset-1 col-sm-10 col-xs-12 profile">{% for edit in edits %}{{ edit.about_me }}{% endfor %}</p>
    {% if not comment_author or user.id == comment_author.id %}
    <p class="col-sm-offset-1 col-sm-10 col-xs-12 profile">Dernière visite le : {{ user.last_login }}</p>
    <div class="col-sm-offset-3 col-sm-6 col-xs-12 profile">Adresse électronique : {{ user.email }}</div>
    <a class="col-sm-offset-3 col-sm-6 col-xs-12 edit-profile" href="{% url 'users:edit_profile' %}">
      Modifier votre profile
    </a>
    {% else %}
    <p class="col-sm-offset-1 col-sm-10 col-xs-12 profile">
      Dernière visite le : {{ comment_author.last_login }}
    </p>
    <div class="col-sm-offset-3 col-sm-6 col-xs-12 profile">
      Adresse électronique : {{ comment_author.email }}
    </div>
    {% endif %}
  </div>

  {% for comment in comments %}
      <hr>
      <div class="div-comment">
        <p class="comment">{{ comment.author }} a laissé un commentaire le {{ comment.date_added|date:"DATE_FORMAT" }} sur <a href="{% url 'catalog:detail_substitute' comment.substitute.id %}">ce produit</a> :</p><br>
        <p class="comment">{{ comment.content }}</p>
      </div>
    
  {% endfor %}
  <div
{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Inscription</h1>
  </div> 
{% endblock %}

{% block section_content %}
  <div class="row">
    <h2 class="col-xs-12">Création de compte</h2>
  </div>
  <div class="row">
    <hr class="col-lg-offset-55 col-xs-1 line">
  </div>
  
  <div class="row">
    <form class="col-sm-offset-4 col-sm-6 col-xs-12" method="post">
      {% csrf_token %}
      {% for field in form %}
      <p class="field-form paragraph">
        {{ field.label_tag }}<br>
        {{ field }}<br>
    
        {% for error in field.errors %}
        <p class="error paragraph">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}
      <button class="btn btn-primary btn-lg submit" type="submit">S'inscrire</button>
    </form>
  </div>
  
  <div class="row">
    <p class="col-sm-offset-2 col-sm-8 col-xs-12 redirect paragraph">Vous avez dèjà un compte? 
      <a href="{% url 'users:log_in' %}">Cliquez ici pour vous connecter!</a>
    </p>
  </div>
{% endblock %}