blog/urls.py
from django.conf.urls import url


urlpatterns = [
]

catalog/urls.py
from django.conf.urls import url
from catalog import views

urlpatterns = [
    url(r'^search/$', views.search, name='search'),
    url(r'^product/(?P<product_id>[0-9]+)/$', views.list_substitute, name='list_substitute'),
    url(r'^substitute/(?P<substitute_id>[0-9]+)/$', views.detail_substitute, name='detail_substitute'),
    url(r'^legal/$', views.legal, name='legal'),
    url(r'^categories/$', views.list_categories, name='list_categories'),
    url(r'^products/$', views.list_products, name='list_products'),
]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import path
from catalog import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url


urlpatterns = [
    # For security reasons, it is essential to change the admin URL because hackers know it
    path('admin', admin.site.urls),
    url(r'^$', views.index, name="index"),
    url(r'^catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^blog/', include(('blog.urls', 'blog'), namespace='blog')),
]

"""if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns"""

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from users import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^log_in/$', views.log_in, name='log_in'),
    url(r'^log_out/$', views.log_out, name="log_out"),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^save_product/(?P<sub_id>[0-9]+)/$', views.save_product, name='save_product'),
    url(r'^list_saved_products/$', views.list_saved_products, name='list_saved_products'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html', email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt', success_url='/users/password_reset/done/'),
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html', success_url='/users/reset/done/'),
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
]

catalog/models.py
from django.db import models
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile
from .openfoodfacts import OpenFoodFacts
import requests
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    nutri_score = models.ImageField(upload_to="images/", db_index=True)
    barcode = models.CharField(max_length=30, db_index=True)
    picture = models.ImageField(upload_to="images/")
    # I made assumption that a product can belong to a single category so as not to complicate things
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Substitute(models.Model):
    name = models.CharField(max_length=255)
    nutri_score = models.ImageField(upload_to="images/")
    barcode = models.CharField(max_length=30)
    url = models.URLField()
    nutrition = models.ImageField(upload_to="images/")
    picture = models.ImageField(upload_to="images/")
    # A product can have several substitutes and a substitute can be the substitute for several products
    composition = models.ManyToManyField(Product, related_name="substitutes")
    user_sub = models.ManyToManyField(User, related_name='user_substitute')

    def __str__(self):
        return self.name


def save_image_from_url(field, url, image, i, save):
    """This function download an image from a given url"""

    r = requests.get(url)
    img_temp = NamedTemporaryFile(delete=True)
    img_temp.write(r.content)
    img_temp.flush()

    field.save(image + str(i) + url[-4:], File(img_temp), save=save)

# I executed this function during the development phase only once in the module views.py to fill the database. If it is executed
# in the module models.py django throws the exeption django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
def insert_data_in_database():
    """This function records the data recover from openfoodfacts in the database of my site"""

    of = OpenFoodFacts('https://fr.openfoodfacts.org/categories&json=1', 'https://fr.openfoodfacts.org/api/v0/produit')
    dict_substitute, dict_cat_prod, list_of_categories = of.get_substitute()

    # recording of categories
    for category_name in list_of_categories:
        print(category_name)
        Category.objects.create(name=category_name)

    # recording of products
    i = 1
    for cat_name, dict_prod in dict_cat_prod.items():
        category = Category.objects.filter(name=cat_name)
        print("CATEGORY: ", category[0])
        for prod_name, values in dict_prod.items():
            p = Product()
            p.name = prod_name
            # values[0] is the nutriscore
            if values[0] == "A":
                p.nutri_score = 'images/nutriscore-a.svg'
            elif values[0] == "B":
                p.nutri_score = 'images/nutriscore-b.svg'
            elif values[0] == "C":
                p.nutri_score = 'images/nutriscore-c.svg'
            elif values[0] == "D":
                p.nutri_score = 'images/nutriscore-d.svg'
            elif values[0] == "E":
                p.nutri_score = 'images/nutriscore-e.svg'
            p.barcode = values[1] #values[1] is the barcode
            p.category = category[0]
            save_image_from_url(p.picture, values[2], "prod", i, True) # values[2] is the url of the image
            i += 1


    # recording of substitutes
    j = 1
    for sub_name, values in dict_substitute.items():
        s = Substitute()
        s.name = sub_name
        if values[0] == "A":
            s.nutri_score = 'images/nutriscore-a.svg'
        elif values[0] == "B":
            s.nutri_score = 'images/nutriscore-b.svg'
        elif values[0] == "C":
            s.nutri_score = 'images/nutriscore-c.svg'
        elif values[0] == "D":
            s.nutri_score = 'images/nutriscore-d.svg'
        elif values[0] == "E":
            s.nutri_score = 'images/nutriscore-e.svg'
        s.barcode = values[1]
        s.url = values[2]
        save_image_from_url(s.nutrition, values[3], "ing_subst", j, False)
        save_image_from_url(s.picture, values[4], "subst", j, True)
        j += 1
        for code in values[-1]: # values[-1] is a list that contains the barcode of products
            print(code)
            p = Product.objects.filter(barcode=code)
            print(p)
            print(p[0])
            s.composition.add(p[0])

catalog/forms.py
from django import forms


class OptionForm(forms.Form):
    CHOICES = (
        ('name', 'nom'),
        ('nutri_score', 'nutriscore croissant'),
        ('-nutri_score', 'nutriscore décroissant'),
    )
    select = forms.ChoiceField(choices=CHOICES, label='Trié par',
                               widget=forms.Select(attrs={'onchange': 'form.submit();'}))

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from catalog.models import Category, Product, Substitute
from django.core.paginator import Paginator, EmptyPage
from catalog.forms import OptionForm
from blog.models import Comment
from blog.forms import CommentForm
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import transaction
from django.http import JsonResponse



def index(request):
    title = 'Accueil'
    description = 'Pur Beurre est un site web d\'une jeune startup fondée par Remy et Colette Tatou, ' \
                  'deux restaurateurs de renom.'
    return render(request, 'base.html', {'title': title, 'description': description})


def list_substitute(request, product_id):
    id = int(product_id)
    product = get_object_or_404(Product, id=id)
    substitutes = product.substitutes.all()

    title = "Liste de substituts"
    message = "Substitut(s) pour le produit : %s" %product.name

    return render(request, 'catalog/search.html',
                  {'substitutes': substitutes, 'title': title,
                   'message': message, 'product': product})


@transaction.atomic
def detail_substitute(request, substitute_id):
    id = int(substitute_id)
    substitute = get_object_or_404(Substitute, id=id)
    title = "%s" %substitute.name
    comments = Comment.objects.filter(substitute=id).order_by('-date_added')
    
    if request.method == 'POST':
        if request.user.is_anonymous:
            messages.add_message(request, messages.ERROR,
                                 'Vous devez vous connecter pour pouvoir poster un message!')
            form = CommentForm()
            return render(request, 'catalog/detail_substitute.html', 
                    {'substitute': substitute, 'title': title, 'form': form, 'comments': comments}) 
        form = CommentForm(request.POST)
        if form.is_valid():
            # We use a transaction so that if one of the requests below fails all previous ones are canceled
            with transaction.atomic():
                comment = form.save(commit=False)
                user = User.objects.filter(id=request.user.id)
                comment.author = user[0]
                comment.substitute = substitute
                comment.save()
                form = CommentForm()
    else:
        form = CommentForm()

    return render(request, 'catalog/detail_substitute.html', 
                    {'substitute': substitute, 'title': title, 'form': form, 'comments': comments})


def search(request):
    title = "Liste des produits"
    if 'query' in request.GET:
        query = request.GET['query']
    # Auto-completion system with AJAX
    if 'content' in request.GET:
        content = request.GET.get('content', None)
        products = Product.objects.filter(name__icontains=content)[0:10].values()
        # We have to return somthing even if no result has been found so that the function break
        if not products.exists():
            return JsonResponse({'status': 'ZERO_RESULTS'})
        else:
            return JsonResponse({'status': 'ok', "products": list(products)})
    
    if not query:
        products = Product.objects.all().order_by('name')
    else:
        products = Product.objects.filter(name__icontains=query).order_by('name')

    if not products.exists():
        products = Product.objects.filter(barcode=query).order_by('name')

    paginator = Paginator(products, 6) # 6 products per page
    if 'page' in request.GET:
        page = request.GET['page']
    else:
        page = 1

    try:
        prods = paginator.page(page)
    except EmptyPage:
        # We return the last page
        prods = paginator.page(paginator.num_pages)

    message = "Résultat(s) pour la recherche : %s" %query

    return render(request, 'catalog/search.html',
                  {'products': prods, 'title': title, 'message': message, 'query': query})


def legal(request):
    title = 'Mentions légales'
    return render(request, 'catalog/legal.html', locals())


def list_categories(request):
    title = 'Liste des catégories'
    categories = Category.objects.all().order_by('id')

    return render(request, 'catalog/list_categories.html', {'title': title, 'categories': categories})


def list_products(request):
    title = 'Liste des produits'
    # cat_id == 0 when user want to display all products
    cat_id = request.GET['cat_id'] if 'cat_id' in request.GET else 0

    cat_id = int(cat_id)
    products = Product.objects.all().order_by('name') if cat_id == 0 else \
               Product.objects.filter(category_id=cat_id).order_by('name')

    paginator = Paginator(products, 50)  # 50 products per page
    page = request.GET['page'] if 'page' in request.GET else 1

    try:
        prods = paginator.page(page)
    except EmptyPage:
        # We return the last page
        prods = paginator.page(paginator.num_pages)

    if request.method == 'POST':
        form = OptionForm(request.POST)
        if form.is_valid():
            order_by = form.cleaned_data.get('select')
            products = Product.objects.all().order_by(order_by) if cat_id == 0 else \
                       Product.objects.filter(category_id=cat_id).order_by(order_by)
            paginator = Paginator(products, 50)
            try:
                prods = paginator.page(page)
            except EmptyPage:
                prods = paginator.page(paginator.num_pages)
            return render(request, 'catalog/list_products.html',
                          {'title': title, 'products': prods, 'form': form, 'order_by': order_by, 'cat_id': cat_id})
    elif 'order_by' in request.GET:
        order_by = request.GET['order_by']
        products = Product.objects.all().order_by(order_by) if cat_id == 0 else \
                   Product.objects.filter(category_id=cat_id).order_by(order_by)
        paginator = Paginator(products, 50)
        try:
            prods = paginator.page(page)
        except EmptyPage:
            prods = paginator.page(paginator.num_pages)
        form = OptionForm(initial={'select': order_by})
        return render(request, 'catalog/list_products.html',
                      {'title': title, 'products': prods, 'form': form, 'order_by': order_by, 'cat_id': cat_id})
    else:
        form = OptionForm()

    return render(request, 'catalog/list_products.html',
                  {'title': title, 'products': prods, 'form': form, 'cat_id': cat_id})

catalog/templates/catalog/detail_substitute.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>{{ substitute.name }}</h1>
  </div> 
{% endblock %}

{% block section_content %}
    <div class="row nutrition">
        <div class="col-sm-offset-1 col-sm-3 col-xs-offset-3 col-xs-5 div-nutriscore">
          <img class="img-nutriscore" src="{{ substitute.nutri_score.url }}" alt='{{ substitute.nutri_score.name }}' />
        </div>
        <div class="col-sm-offset-2 col-sm-4 col-xs-offset-3 col-xs-6">
          <p class="repere paragraph">Repères nutritionnels pour 100g :</p>
          <img class="img-nutrition" src="{{ substitute.nutrition.url }}" alt="{{ substitute.nutrition.name }}" />
        </div>
    </div>
    <div class="row div-link">
      <a class="col-xs-offset-2 col-xs-8 link-openfood" href="{{ substitute.url }}">Voir la fiche d'OpenFoodFacts</a>
    </div>
    <div class="row">
      <form class="col-lg-12" method="post">
        {% csrf_token %}
          <div class="row">
            {% for field in form %}
            <div class="col-lg-12">
              <p class="leave-comment">Laisser un commentaire pour ce produit :</p></br> 
              {{ field }}
            </div>
            {% endfor %}
            <input class="btn btn-primary btn-lg submit pull-right" type="submit" value="Soumettre" />
          </div>  
      </form>
    </div>
    
    {% for comment in comments %}
      <div class="row">
        <hr>
        <div class="div-comment">
          <p class="comment">
            <a href="{% url 'users:profile' %}?comment_author_id={{ comment.author.id }}">{{ comment.author }}</a>
             a dit le {{ comment.date_added|date:"DATE_FORMAT" }} :
          </p><br>
          <p class="comment">{{ comment.content }}</p>
        </div>
      </div>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/legal.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Mentions légales</h1>
  </div> 
{% endblock %}

{% block section_content %}
  <div class="row">
    <h2 class="col-xs-12">Droits d'auteurs</h2>
  </div>
  <div class="row">
    <hr class="col-lg-offset-55 col-xs-1 line">
  </div>

  <div class="row legal">
    Logo Pur beurre par <a class="link-legal" href="https://company-82435.frontify.com/d/6Yy9WFJdtp8j/pur-beurre-style-guide#/elements-basiques/marque-et-logo">Pur Beurre - Charte Graphique</a>
  </div>
  <div class="row legal">
    Logo de carotte par <a class="link-legal" href="https://thenounproject.com/term/carrot/29691/">Fabien Jouin</a>
  </div>
  <div class="row legal">
    Logo de connexion par <a class="link-legal" href="https://thenounproject.com/search/?q=login&i=2401379" >Alena Artemova</a>
  </div>
  <div class="row legal">
    Logo de deconnexion par <a class="link-legal" href="https://thenounproject.com/search/?q=logout&i=1251677" >Kamal</a>
  </div>
  <div class="row legal">
    Fond de page par <a class="link-legal" href="https://unsplash.com/photos/eqsEZNCm4-c">Olenka Kotyk</a>
  </div>
  <div class="row legal">
    Images de colette et remy par <a class="link-legal" href="https://company-82435.frontify.com/d/6Yy9WFJdtp8j/pur-beurre-style-guide#/langage-visuel/photographies">Pur Beurre - Charte Graphique</a>
  </div>
  <div class="row legal">
    Les données sont issues de l'API du site <a class="link-legal" href="https://fr.openfoodfacts.org/">OpenFoodFacts</a>
  </div>

{% endblock %}

catalog/templates/catalog/list_categories.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Liste des catégories</h1>
  </div> 
{% endblock %}

{% block section_content %}
  <table class="table table-bordered table-striped table-condensed category">
    <thead>
      <tr>
        <th>Ctagories</th>
        <th>Produits</th>
      </tr>
    </thead>
  
    <tbody>
      {% for category in categories %}
        <tr>
          <td><a href="{% url 'catalog:list_products' %}?cat_id={{ category.id }}">{{ category.name }}</a></td>
          <!-- category.product_set.all.count is the number of products that the category contains-->
          <td class="pull-left">{{ category.product_set.all.count }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  
{% endblock %}

catalog/templates/catalog/list_products.html
{% extends 'base.html' %}

{% block query %}
  <div class=" container starter-template">
    <h1>Liste des produits</h1>
  </div> 
{% endblock %}

{% block section_content %}
  <form class="col-lg-5 pull-right" method="post">
    {% csrf_token %}
    {% for field in form %}
      <p class="field-form paragraph">
        {{ field.label_tag }}
        {{ field }}
      </p>
    {% endfor %}
  </form>
  
  <div class="col-sm-12 table-responsive">
    <table class="table table-bordered table-striped table-condensed category">
      <thead>
        <tr>
          <th>Produits</th>
          <th>Nutriscore</th>
          <th>codebare</th>
          <th>catégorie</th>
        </tr>
      </thead>
    
      <tbody>
        {% for product in products %}
          <tr>
            <td><a class="pull-left" href="{% url 'catalog:search' %}?query={{ product.barcode }}" title="voir les substituts de ce produit">{{ product.name }}</a></td>
            <td>
              {% if 'nutriscore-a.svg' in product.nutri_score.url %}A
              {% elif 'nutriscore-b.svg' in product.nutri_score.url %}B
              {% elif 'nutriscore-c.svg' in product.nutri_score.url %}C
              {% elif 'nutriscore-d.svg' in product.nutri_score.url %}D
              {% elif 'nutriscore-e.svg' in product.nutri_score.url %}E
              {% endif %}
            </td>
            <td>{{ product.barcode }}</td>
            <td>{{ product.category.name }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="pagination">
      {% if products.has_previous %}
        <a href="?page={{ products.previous_page_number }}{% if order_by %}&order_by={{ order_by }}{% endif %}&cat_id={{ cat_id }}">Précédente</a> -
      {% endif %}
    
      <span class="current">
        Page {{ products.number }} sur 
        <a href="?page={{ products.paginator.num_pages }}{% if order_by %}&order_by={{ order_by }}{% endif %}&cat_id={{ cat_id }}">{{ products.paginator.num_pages }}</a>
      </span>
    
      {% if products.has_next %}
        - <a href="?page={{ products.next_page_number }}{% if order_by %}&order_by={{ order_by }}{% endif %}&cat_id={{ cat_id }}">Suivante</a>
      {% endif %}
    </div>
  </div>
  
  
{% endblock %}

catalog/templates/catalog/search.html
{% extends 'base.html' %}
{% block query %}
  <div class=" container starter-template">
    <h1>
      {% if query %}
        {{ query.capitalize }}
      {% elif product %}
        {{ product.name.capitalize }}
      {% endif %}
    </h1>
  </div> 
{% endblock %}

{% block section_content %}
  <div class="row">
    <h2 class="col-xs-12">{{ message }}</h2>
  </div>
  <div class="row">
    <hr class="col-lg-offset-55 col-xs-1 line">
  </div>
  
  <div class="row">
      <h3 class="col-xs-12">
        {% if products %}
        Choisissez le produit que vous voulez substituer
        {% elif substitutes %}
        Vous pouvez remplacer votre produit par le(s) produit(s) suivant(s) :
        {% endif %}
      </h2>
  </div>

  {% if products|length_is:"0" %}
  <div class="row">
    <h3>Votre recherche n'a donné aucun résultat</h3>
  </div>
  {% elif substitutes|length_is:"0" %}
    <div class="row">
      <h3>Le produit rechrché n'a pas de substitut de meilleur qualité</h3>
    </div>
  {% else %} 
  
    {% if products %}
      <div class="row div-products">
        {% for product in products %}
          <div class="col-sm-4">
            <div class="row div-product">
              <div class="col-sm-12 coloffset2 col-xs-8">
                <a class="link-product" href="{% url 'catalog:list_substitute' product.id %}" title="{{ product.name }}">
                  <div class="div-img">
                    <img class="img-product" src="{{ product.picture.url }}" alt="{{ product.picture.name }}" />
                  </div>
                  <span class="nutriscore">
                    {% if 'nutriscore-a.svg' in product.nutri_score.url %}A
                    {% elif 'nutriscore-b.svg' in product.nutri_score.url %}B
                    {% elif 'nutriscore-c.svg' in product.nutri_score.url %}C
                    {% elif 'nutriscore-d.svg' in product.nutri_score.url %}D
                    {% elif 'nutriscore-e.svg' in product.nutri_score.url %}E
                    {% endif %}

                  </span>
                  <div class="product-name">{{ product.name|truncatewords:10 }}</div>
                </a>  
              </div> 
            </div> 
          </div>
          {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
        {% endfor %}

      </div>

      <div class="row pagination">
        {% if products.has_previous %}
          <a href="?page={{ products.previous_page_number }}&query={{ query }}">Précédente</a> -
        {% endif %}
      
        <span class="current">
          Page {{ products.number }} sur 
          <a href="?page={{ products.paginator.num_pages }}&query={{ query }}">{{ products.paginator.num_pages }}</a>
        </span>
      
        {% if products.has_next %}
          - <a href="?page={{ products.next_page_number }}&query={{ query }}">Suivante</a>
        {% endif %}
        
      </div>
    
    {% elif substitutes %}
      <div class="row div-products">
        {% for substitute in substitutes %}
          <div class="col-sm-4">
            <div class="row div-product">
              <div class="col-sm-12 coloffset2 col-xs-8">
                <a class="link-product" href="{% url 'catalog:detail_substitute' substitute.id %}" title="{{ substitute.name }}">
                  <div class="div-img">
                    <img class="img-product" src="{{ substitute.picture.url }}" alt="{{ substitute.picture.name }}" />
                  </div>
                  <span class="nutriscore">
                    {% if 'nutriscore-a.svg' in substitute.nutri_score.url %}A
                    {% elif 'nutriscore-b.svg' in substitute.nutri_score.url %}B
                    {% elif 'nutriscore-c.svg' in substitute.nutri_score.url %}C
                    {% elif 'nutriscore-d.svg' in substitute.nutri_score.url %}D
                    {% elif 'nutriscore-e.svg' in substitute.nutri_score.url %}E
                    {% endif %}
                  </span>
                  <div class="product-name">{{ substitute.name|truncatewords:10 }}</div>
                </a>  
                <a href="{% url 'users:save_product' substitute.id  %}">
                  <i class="fas fa-save"> Sauvegarder</i> 
                </a>
              </div> 
            </div> 
          </div>
          {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
        {% endfor %}
      </div>

    {%endif%}
  {% endif %}
{% endblock %}